### ISSUE TITLE
Geom opt input structure

### ISSUE THREAD

**Issue by tommyh-ECL** [cloudlab-cmu/cloudcompchem#10]
Develop geometry opt input JSON payload (look at energy payload for reference)

**Comment by yiwenwang47** [comment]
[https://github.com/cloudlab-cmu/cloudcompchem/blob/d96037f882f05d50a9a5818400822c46203175df/cloudcompchem/models.py#L96](url)

**Comment by yiwenwang47** [comment]
Need to modify the input arguments into separate categories (each initialized by calling a different class).

**Comment by yiwenwang47** [comment]
config, molecule
